name: deploy-eks

on:
  workflow_call:
    inputs:
      kube_namespace:
        type: string
        required: true
        description: Kubernetes Namespace
      kube_context:
        type: string
        required: true
        description: Kubernetes Context
      deployment_name:
        type: string
        required: true
        description: EKS deployment name
      docker_repository:
        type: string
        required: true
        description: Docker respository name
      image_tag:
        type: string
        required: true
        description: The docker image tag
      runner:
        type: string
        required: false
        description: Self hosted runner label
        default: "['ubuntu-20.04']"
      check_rollout_status:
        type: boolean
        required: false
        description: Add step to check rolled out status
        default: false

    secrets:
      kube_config_data:
        required: true
        description: Kubernetes Config
      aws_access_key_id:
        required: true
        description: AWS Access ID
      aws_secret_access_key:
        required: true
        description: AWS Secret Key
      docker_registry:
        required: true
        description: Docker registry

env:
  AWS_REGION: ap-southeast-2
  KUBE_CONFIG_DATA: ${{ secrets.kube_config_data }}
  KUBE_NAMESPACE: ${{ inputs.kube_namespace }}
  KUBECTL_VERSION: ${{ inputs.kubectl_version }}
  IAM_VERSION: ${{ inputs.iam_version }}

jobs:
  deploy_eks:
    runs-on: ${{ fromJson(inputs.runner) }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{env.AWS_REGION }}

      - name: Login To Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy To AWS EKS Cluster
        uses: ./.git-composite-action/aws/eks/run-kubectl@v1.0.4
        env:
          IMAGE: ${{ secrets.docker_registry }}/${{ inputs.docker_repository }}:${{ inputs.image_tag }}
        with:
          kube_context: ${{ inputs.kube_context }}
          kube_arg: set image -n ${KUBE_NAMESPACE} deployment/${{ inputs.deployment_name }} ${{ inputs.deployment_name }}=${IMAGE}
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          aws_default_region: ${{ env.AWS_REGION }}

      - name: Verify Deployment
        if: ${{ inputs.check_rollout_status == true }}
        uses: ./.git-composite-action/aws/eks/run-kubectl@v1.0.4
        with:
          kube_context: ${{ inputs.kube_context }}
          kube_arg: rollout status -n ${KUBE_NAMESPACE} deployment/${{ inputs.deployment_name }}
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          aws_default_region: ${{ env.AWS_REGION }}
