name: Helm Install/Upgrade

on:
  workflow_call:
    inputs:
      release:
        type: string
        required: true
        description: Umbrella chart name      
      chart-name:
        type: string
        required: true
        description: The target service name
      target-namespace:
        required: true
        type: string
        description: Target namespace (trav-taas)
      target-env:
        required: true
        type: string        
        description: Supported values (dev,stg,uat,prd)


      # Optional Inputs
      aws-region:
        required: false
        type: string        
        default: ap-southeast-2
        description: aws region (default ap-southeast-2)
      value-file1:
        type: string        
        required: false
        description: "Additional value1"
      value-file2:
        type: string        
        required: false
        description: "Additional value2"
      runner:
        type: string
        required: false
        description: Self hosted runner label
        default: "['ubuntu-20.04']"
      notify-on-success:
        type: boolean
        required: false
        description: Send notification on success
        default: false
      notify-on-fail:
        type: boolean
        required: false
        description: Send notification on fail
        default: false
      notification-channel:
        type: string
        required: false
        description: Target slack channel
        default: alert-information
    
    
    secrets:
      kube-config:
        required: true
        description: base64 of kubernetes configuration
      github-token:
        required: true
        description: The github token used to fetch ci environment
      aws-role:
        required: true
        description: AWS Assumed Role

jobs:
  upgrade-helm-deployment:
    runs-on: ${{ fromJson(inputs.runner) }}
    steps:
      - name: Checkout git-composite-action
        uses: actions/checkout@v3
        with:
          repository: travlrcom/git-composite-action
          ref: v1.3.0
          token: ${{ secrets.github-token }}
          path: .git-composite-action

      - name: Install/Upgrade Helm Release
        uses: ./.git-composite-action/helm/upgrade
        with:
          aws-role: ${{ secrets.aws-role }}
          github-token:  ${{ secrets.github-token }}
          kube-config-data:  ${{ secrets.kube-config }}
          release: ${{ inputs.release }}
          namespace: ${{ inputs.target-namespace }}
          value-file1: ${{ inputs.value-file1 }}
          value-file2: ${{ inputs.value-file2 }}          
          chart: env/${{ inputs.target-env }}/${{ inputs.target-namespace }}/${{ inputs.chart-name }}

      - name: Send Success Notification
        if: success() && inputs.notify-on-success
        uses: ./.git-composite-action/slack/send-notif
        with:
          aws-role: ${{ secrets.aws-role }}
          subject: ":beers: [GITHUB] Service *${{ inputs.release }}* Successfully Deployed :beers:"
          channel: ${{ inputs.notification-channel }}

      - name: Send Fail Notification
        if:  failure() && inputs.notify-on-fail
        uses: ./.git-composite-action/slack/send-notif
        with:
          aws-role: ${{ secrets.aws-role }}
          subject: ":rotating_light: [GITHUB] Service *${{ inputs.release }}* Deployment Failed :rotating_light:"
          channel: ${{ inputs.notification-channel }}