name: Abort All Argo Rollout

on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: true
        description: Namespace for rollout abort
      runner:
        type: string
        required: false
        description: Self hosted runner label
        default: "['ubuntu-20.04']"
      aws-region:
        type: string
        required: false
        default: ap-southeast-2
        description: aws region (default ap-southeast-2)

    secrets:
      aws-role:
        required: true
        description: AWS role to assume
      kube-config-data:
        required: true
        description: Base 64 kube config data

jobs:
  argo-rollout-abort:
    runs-on: ${{ fromJson(inputs.runner) }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.aws-role }}
          aws-region: ${{ inputs.aws-region }}
          
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1.5.3
        
      - name: Abort All Argo Rollout
        shell: bash
        env:
          IMAGE_NAME: 269461048441.dkr.ecr.ap-southeast-2.amazonaws.com/travlr-ci:1.0.0-kube-argo-rollout-abort
        run: |
          docker run --rm \
          -e "AWS_DEFAULT_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "AWS_SESSION_TOKEN" \
          -e KUBECONFIG_DATA=${{ secrets.kube-config-data }} \
          -e NAMESPACE=${{ inputs.namespace }} \
          $IMAGE_NAME
