name: Slack Send Workflow Result Notification

on:
  workflow_call:
    inputs:
      send-on-success:
        type: boolean
        required: false
        default: false
      send-on-failure:
        type: boolean
        required: false
        default: false        
      notification-channel:
        type: string
        required: false
        description: Target slack channel
        default: alert-information
      aws-region:
        required: false
        type: string
        default: ap-southeast-2
        description: aws region (default ap-southeast-2)        
  
      runner:
        type: string
        required: false
        description: Self hosted runner label
        default: "['ubuntu-20.04']"

    secrets:
      github-token:
        required: true
        description: The github token used to fetch ci environment
      aws-role:
        required: true
        description: AWS Assumed Role    

jobs:
  send-slack-wf-result:
    runs-on: ${{ fromJson(inputs.runner) }}
    steps:
      - name: Checkout git-composite-action
        uses: actions/checkout@v3
        with:
          repository: travlrcom/git-composite-action
          ref: v1.3.0
          token: ${{ secrets.github-token }}
          path: .git-composite-action
       
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.aws-role}}
          aws-region: ${{ inputs.aws-region }}
         
      - name: Send Success Notification
        if: ${{ inputs.send-on-success }}
        uses: ./.git-composite-action/slack/send-notif
        with:
          aws-role: ${{ secrets.aws-role }}
          subject: ":beers: [GITHUB] Deploy Success: *${{ github.workflow }}*  :beers:"
          channel: ${{ inputs.notification-channel }}

      - name: Send Fail Notification
        if: ${{ inputs.send-on-failure }}
        uses: ./.git-composite-action/slack/send-notif
        with:
          aws-role: ${{ secrets.aws-role }}
          subject: ":rotating_light: [GITHUB] Deploy Failed: *${{ github.workflow }}* :rotating_light:"
          channel: ${{ inputs.notification-channel }}