name: verify-deployment

on:
  workflow_call:
    inputs:
      kube_namespace:
        type: string
        required: true
        description: Kubernetes Namespace
      kube_context:
        type: string
        required: true
        description: Kubernetes Context
      deployment_name:
        type: string
        required: true
        description: EKS deployment name
      runner:
        type: string
        required: false
        description: Self hosted runner label
        default: "['ubuntu-20.04']"

    secrets:
      aws_access_key_id:
        required: true
        description: AWS Access ID
      aws_secret_access_key:
        required: true
        description: AWS Secret Key
      gpr_token:
        required: true
        description: Github Token

env:
  AWS_REGION: ap-southeast-2

jobs:
  verify_deployment:
    runs-on: ${{ fromJson(inputs.runner) }}
    steps:
      - name: Checkout git-composite-action
        uses: actions/checkout@v3
        with:
          repository: travlrcom/git-composite-action
          ref: main
          token: ${{ secrets.gpr_token }}
          path: .git-composite-action

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{env.AWS_REGION }}

      - name: Login To Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Verify Deployment
        uses: ./.git-composite-action/aws/eks/run-kubectl
        with:
          kube_context: ${{ inputs.kube_context }}
          kube_arg: rollout status -n ${{ inputs.kube_namespace }} deployment/${{ inputs.deployment_name }}
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          aws_default_region: ${{ env.AWS_REGION }}
