name: verify-deployment

on:
  workflow_call:
    inputs:
      kube_namespace:
        type: string
        required: true
        description: Kubernetes Namespace
      deployment_name:
        type: string
        required: true
        description: EKS deployment name
      kubectl_version:
        type: string
        required: false
        description: The kubectl version
        default: 'v1.24.0'
      iam_version:
        type: string
        required: false
        description: The iam version
        default: '0.5.7'
      runner:
        type: string
        required: false
        description: Self hosted runner label
        default: "['ubuntu-20.04']"

    secrets:
      kube_config_data:
        required: true
        description: Kubernetes Config
      aws_access_key_id:
        required: true
        description: AWS Access ID
      aws_secret_access_key:
        required: true
        description: AWS Secret Key

env:
  AWS_REGION: ap-southeast-2
  KUBE_CONFIG_DATA: ${{ secrets.kube_config_data }}
  KUBECTL_VERSION: ${{ inputs.kubectl_version }}
  IAM_VERSION: ${{ inputs.iam_version }}

jobs:
  verify_deployment:
    runs-on: ${{ fromJson(inputs.runner) }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{env.AWS_REGION }}

      - name: Verify Deployment
        uses: kodermax/kubectl-aws-eks@1.1.0
        with:
          args: rollout status -n ${{ inputs.kube_namespace }} deployment/${{ inputs.deployment_name }}
