name: verify-deployment

on:
  workflow_call:
    inputs:
      kube_namespace:
        type: string
        required: true
        description: Kubernetes Namespace
      kube_context:
        type: string
        required: true
        description: Kubernetes Context
      deployment_name:
        type: string
        required: true
        description: EKS deployment name
      runner:
        type: string
        required: false
        description: Self hosted runner label
        default: "['ubuntu-20.04']"

    secrets:
      kube_config_data:
        required: true
        description: Kubernetes Config
      aws_access_key_id:
        required: true
        description: AWS Access ID
      aws_secret_access_key:
        required: true
        description: AWS Secret Key

env:
  AWS_REGION: ap-southeast-2
  KUBE_CONFIG_DATA: ${{ secrets.kube_config_data }}
  KUBECTL_VERSION: ${{ inputs.kubectl_version }}
  IAM_VERSION: ${{ inputs.iam_version }}

jobs:
  verify_deployment:
    runs-on: ${{ fromJson(inputs.runner) }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{env.AWS_REGION }}

      - name: Login To Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Verify Deployment
        if: ${{ inputs.check_rollout_status == true }}
        uses: ./.git-composite-action/aws/eks/run-kubectl@v1.0.4
        with:
          kube_context: ${{ inputs.kube_context }}
          kube_arg: rollout status -n ${KUBE_NAMESPACE} deployment/${{ inputs.deployment_name }}
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          aws_default_region: ${{ env.AWS_REGION }}
